trigger:
  - master

resources:
  containers:
    - container: ubuntu1804
      image: yugabytedb/yb_build_infra_ubuntu1804:v2019-07-24T14_48_25_mbautin
      options: "--cap-add=SYS_PTRACE"

    - container: ubuntu1904_gcc7
      image: yugabytedb/yb_build_infra_ubuntu1904_gcc7:v2019-07-11T23_55_23_mbautin
      options: "--cap-add=SYS_PTRACE"

    - container: centos7
      image: yugabytedb/yb_build_infra_centos7:v2019-09-01T14_58_09_mbautin
      options: "--cap-add=SYS_PTRACE"

jobs:
  - job: RunInContainer
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 0

    strategy:
      matrix:
        ubuntu1804:
          containerResource: ubuntu1804
        centos7:
          containerResource: centos7
        ubuntu1904_gcc7:
          containerResource: ubuntu1904_gcc7

    container: $[ variables['containerResource'] ]

    steps:
      - script: |
          sudo mkdir -p /opt/yb-build
          sudo chown yugabyte-ci /opt/yb-build
          sudo mkdir -p /opt/yb-build/thirdparty
          sudo chown yugabyte-ci /opt/yb-build/thirdparty
          checkout_dir=$PWD
          chmod -R a+r "$checkout_dir"
          find "$checkout_dir" -executable -type f -exec chmod a+x {} \;
          sudo -u yugabyte-ci -E /bin/bash -c "cd '$checkout_dir' ./build_and_release.sh"
        env:
          GITHUB_TOKEN: $(yugabyte.githubToken)
