version: 2.1

jobs:
  build:
    parameters:
      docker_image:
        type: string

    parallelism: 2

    docker:
      - image: << parameters.docker_image >>

    steps:
      - checkout:
          path: /opt/yb-build/thirdparty/checkout

      - run:
          name: Build YugabyteDB third-party dependencies
          working_directory: /opt/yb-build/thirdparty/checkout
          command: ./build_and_release.sh

workflows:
  build-release:
    jobs:
      - build:
          name: build-centos
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-06-03T06_49_38
      - build:
          name: build-ubuntu
          docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2020-06-10T22_57_55
