version: 2.1

jobs:
  build:
    parameters:
      docker_image:
        type: string
      yb_thirdparty_build_type:
        type: string

    # Need docker run with SYS_PTRACE for address sanitizer to work
    machine:
      enabled: true

    steps:
      - checkout

      - run:
          name: Build YugabyteDB third-party dependencies
          command: |
            df -H .
            checkout_dir=$PWD
            echo "Building in directory: $checkout_dir"
            echo "YB_BUILD_THIRDPARTY_EXTRA_ARGS=${YB_BUILD_THIRDPARTY_EXTRA_ARGS:-undefined}"
            docker run -t \
              --cap-add=SYS_PTRACE \
              -e GITHUB_TOKEN \
              -e YB_BUILD_THIRDPARTY_EXTRA_ARGS \
              -e CIRCLE_PULL_REQUEST \
              "--mount=type=bind,src=$checkout_dir,dst=/opt/yb-build/thirdparty/checkout" \
              << parameters.docker_image >> \
              bash -c "
                cd /opt/yb-build/thirdparty/checkout
                export YB_THIRDPARTY_BUILD_TYPE=<< parameters.yb_thirdparty_build_type >>
                ./build_and_release.sh
              "

workflows:
  build-release:
    jobs:
      - build:
          name: build-centos-linuxbrew
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-10-14T22_56_28
          yb_thirdparty_build_type: linuxbrew
      - build:
          name: build-centos-devtoolset-8
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-10-14T22_56_28
          yb_thirdparty_build_type: devtoolset-8
      - build:
          name: build-ubuntu
          docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2020-10-13T22_08_51
          yb_thirdparty_build_type: default
