version: 2.1

jobs:
  build:
    parameters:
      docker_image:
        type: string
      archive_name_suffix:
        type: string
      build_thirdparty_args:
        type: string
        default: ""

    # Need docker run with SYS_PTRACE for address sanitizer to work
    machine:
      enabled: true

    steps:
      - checkout

      - run:
          name: Build YugabyteDB third-party dependencies
          command: |
            df -H .
            checkout_dir=$PWD
            echo "Building in directory: $checkout_dir"
            echo "YB_BUILD_THIRDPARTY_EXTRA_ARGS=${YB_BUILD_THIRDPARTY_EXTRA_ARGS:-undefined}"
            docker run -t \
              --cap-add=SYS_PTRACE \
              -e GITHUB_TOKEN \
              -e YB_BUILD_THIRDPARTY_EXTRA_ARGS \
              -e CIRCLE_PULL_REQUEST \
              "--mount=type=bind,src=$checkout_dir,dst=/opt/yb-build/thirdparty/checkout" \
              << parameters.docker_image >> \
              bash -c "
                set -euo pipefail
                cd /opt/yb-build/thirdparty/checkout
                export YB_THIRDPARTY_ARCHIVE_NAME_SUFFIX='<< parameters.archive_name_suffix >>'
                export YB_BUILD_THIRDPARTY_ARGS='<< parameters.build_thirdparty_args >>'
                ./build_and_release.sh
              "

workflows:
  build-release:
    jobs:
      - build:
          name: centos-linuxbrew-gcc5
          archive_name_suffix: linuxbrew
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-11-01T06_02_36
      - build:
          name: centos-gcc-devtoolset-8
          archive_name_suffix: devtoolset-8
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-11-01T06_02_36
          build_thirdparty_args: "--devtoolset=8"
      - build:
          name: centos-gcc-devtoolset-9
          archive_name_suffix: devtoolset-9
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-11-01T06_02_36
          build_thirdparty_args: "--devtoolset=9"
      - build:
          name: ubuntu-gcc7
          archive_name_suffix: "gcc7"
          docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2020-11-01T06_02_36
      - build:
          name: ubuntu-gcc8
          archive_name_suffix: "gcc8"
          docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2020-11-01T06_02_36
          build_thirdparty_args: "--compiler-suffix=-8"
      - build:
          name: ubuntu-clang10
          archive_name_suffix: clang10
          docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2020-11-01T06_02_36
          build_thirdparty_args: >-
            --single-compiler-type=clang
            --compiler-prefix=/usr
            --compiler-suffix=-10
