version: 2.1

jobs:
  build:
    parameters:
      name:
        type: string
      docker_image:
        type: string
      build_thirdparty_args:
        type: string
        default: ""

    # Need docker run with SYS_PTRACE for address sanitizer to work
    machine:
      enabled: true

    steps:
      - checkout

      - run:
          name: Build YugabyteDB third-party dependencies
          command: |
            df -H .
            checkout_dir=$PWD
            echo "Building in directory: $checkout_dir"
            echo "YB_BUILD_THIRDPARTY_EXTRA_ARGS=${YB_BUILD_THIRDPARTY_EXTRA_ARGS:-undefined}"
            docker run -t \
              --cap-add=SYS_PTRACE \
              -e GITHUB_TOKEN \
              -e YB_BUILD_THIRDPARTY_EXTRA_ARGS \
              -e CIRCLE_PULL_REQUEST \
              "--mount=type=bind,src=$checkout_dir,dst=/opt/yb-build/thirdparty/checkout" \
              << parameters.docker_image >> \
              bash -c "
                cd /opt/yb-build/thirdparty/checkout
                export YB_THIRDPARTY_BUILD_NAME=<< parameters.name >>
                export YB_BUILD_THIRDPARTY_ARGS=<< parameters.build_thirdparty_args >>
                ./build_and_release.sh
              "

workflows:
  build-release:
    jobs:
      - build:
          name: build-centos-linuxbrew
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-10-17T18_09_58
      - build:
          name: build-centos-devtoolset-8
          docker_image: yugabyteci/yb_build_infra_centos7:v2020-10-17T18_09_58
          build_thirdparty_args: "--devtoolset=8"
      - build:
          name: build-ubuntu
          docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2020-10-13T22_08_51
      - build:
          name: build-ubuntu-clang10
          docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2020-10-13T22_08_51
          build_thirdparty_args: "--single-compiler-type=clang --compiler-suffix=-10"
