name: Linux

# TODO: deduplicate this across multiple workflow files.
on:
  push:
    branches:
      - master
      - 2.4

    paths-ignore:
      - README.md

  # Run tests for any PRs.
  pull_request:
    branches:
      - master
      - 2.4

    paths-ignore:
      - README.md

jobs:
  build:
    name: ${{ matrix.archive_name_suffix }}
    runs-on: ubuntu-20.04
    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip')) ||
      github.event_name == 'pull_request'
    strategy:
      # To avoid terminating all jobs when one job fails.
      fail-fast: false
      matrix:
        include:
          - name: centos7-linuxbrew-gcc5
            archive_name_suffix: centos7-linuxbrew
            docker_image: yugabyteci/yb_build_infra_centos7:v2021-03-26T05_02_29
            build_thirdparty_args: "--toolchain=linuxbrew"

          - name: centos7-gcc-devtoolset-8
            archive_name_suffix: centos7-devtoolset-8
            docker_image: yugabyteci/yb_build_infra_centos7:v2021-03-26T05_02_29
            build_thirdparty_args: "--devtoolset=8"

          - name: centos7-gcc-devtoolset-9
            archive_name_suffix: centos7-devtoolset-9
            docker_image: yugabyteci/yb_build_infra_centos7:v2021-03-26T05_02_29
            build_thirdparty_args: "--devtoolset=9"

          - name: centos7-clang7
            archive_name_suffix: centos7-clang7
            docker_image: yugabyteci/yb_build_infra_centos7:v2021-03-26T05_02_29
            build_thirdparty_args: --toolchain=llvm7

          - name: centos7-clang11
            archive_name_suffix: centos7-clang11
            docker_image: yugabyteci/yb_build_infra_centos7:v2021-03-26T05_02_29
            build_thirdparty_args: --toolchain=llvm11

          - name: centos7-clang12
            archive_name_suffix: centos7-clang12
            docker_image: yugabyteci/yb_build_infra_centos7:v2021-03-26T05_02_29
            build_thirdparty_args: --toolchain=llvm12

          - name: ubuntu1804-gcc7
            archive_name_suffix: ubuntu1804-gcc7
            docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2021-03-26T05_02_28
            build_thirdparty_args: >-
              --compiler-prefix=/usr
              --single-compiler-type=gcc
              --compiler-suffix=-7

          - name: ubuntu1804-gcc8
            archive_name_suffix: ubuntu1804-gcc8
            docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2021-03-26T05_02_28
            build_thirdparty_args: >-
              --compiler-prefix=/usr
              --single-compiler-type=gcc
              --compiler-suffix=-8

          - name: ubuntu1804-clang10
            archive_name_suffix: ubuntu1804-clang10
            docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2021-03-26T05_02_28
            build_thirdparty_args: >-
              --single-compiler-type=clang
              --compiler-prefix=/usr
              --compiler-suffix=-10

          - name: ubuntu1804-clang11
            archive_name_suffix: ubuntu1804-clang11
            docker_image: yugabyteci/yb_build_infra_ubuntu1804:v2021-03-26T05_02_28
            build_thirdparty_args: >-
              --single-compiler-type=clang
              --compiler-prefix=/usr
              --compiler-suffix=-11

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Build
        run: ./.github/workflows/linux_build.sh
        env:
          YB_DOCKER_IMAGE: ${{ matrix.docker_image }}
          YB_THIRDPARTY_ARCHIVE_NAME_SUFFIX: ${{ matrix.archive_name_suffix }}
          YB_BUILD_THIRDPARTY_ARGS: ${{ matrix.build_thirdparty_args }}
