name: macOS

# TODO: deduplicate this across multiple workflow files.
on:
  push:
    branches:
      - master
      - 2.6

    paths-ignore:
      - README.md

  # Run tests for any PRs.
  pull_request:
    branches:
      - master
      - 2.6

    paths-ignore:
      - README.md

env:
  GITHUB_ORG_AND_REPO: "${{ github.repository }}"

jobs:
  build:
    runs-on: macos-10.15
    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip')) ||
      github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2

      - name: Build YugabyteDB third-party dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          YB_THIRDPARTY_ARCHIVE_NAME_SUFFIX: macos
        run: ./.github/workflows/macos_build.sh
